name: Azure Deployment

on:
  push:
    branches:
      - main

env:
  SP_CLIENT_ID: "a8316d52-e662-4ff4-84ba-449362b6362f"
  SP_CLIENT_SECRET: "ny98Q~qC5bEoAHwGEeAlDUcdukfYsjlHvofxSaKF"
  SP_TENANT_ID: "c6d45d93-3646-435c-91e4-70f5ec9fd82e"
  AZURE_SUBSCRIPTION_NAME:  ${{ secrets.AZURE_SUBSCRIPTION_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell script
        uses: microsoft/powershell@v1
        with:
          enable-AzPSSession: true
          pwsh: 'pwsh'
          workingDirectory: .
          script: |
            .\createDatabase.ps1
            # Remember to replace any variables with their actual values
