name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Azure CLI
      uses: azure/login@v1
      
    - name: Run PowerShell script
      uses: microsoft/powershell@v1
      with:
        pwsh: 'pwsh'
        workingDirectory: .
        script: |
          .\gitrepo\sidd\createDatabase.ps1
          # Remember to replace any variables with their actual values

